channels:
- anaconda
- conda-forge
dependencies:
- python=3.6.2
- pip:
  - azureml-core==1.18.0.post1
  - azureml-defaults==1.18.0
  - azureml-telemetry==1.18.0
  - azureml-train-restclients-hyperdrive==1.18.0
  - azureml-train-core==1.18.0
  - azureml-widgets==1.18.0
  - azureml-pipeline-core==1.18.0
  - azureml-pipeline-steps==1.18.0
  - azureml-opendatasets==1.18.0
  - azureml-automl-core==1.18.0
  - azureml-automl-runtime==1.18.0
  - azureml-train-automl-client==1.18.0
  - azureml-train-automl-runtime==1.18.0.post1
  - azureml-train-automl==1.18.0
  - azureml-train==1.18.0
  - azureml-sdk==1.18.0
  - azureml-interpret==1.18.0
  - azureml-tensorboard==1.18.0
  - azureml-mlflow==1.18.0
  - mlflow
  - sklearn-pandas
- pandas
- numpy
- tqdm
- scikit-learn
- matplotlib
name: azureml_8fd3f9f199f53e0d69da685b735ef9f1
